# Este archivo .yml define ciertas configuraciones para la ejecución del sistema
# Configuraciones exclusivas del Manager
manager:
  # Define cada cuantos segundo el Manager enviará un broadcast UDP a la red para sondear agentes
  udp_request_delay: 3
  # Cantidad de archivos de tests a ejecutar en cada tanda
  test_files_by_runner: 30
  # Configuraciones que definen que barras se muestran o no
  bar:
    # Mostrar o no el progreso de envío de código fuente a los agentes
    share_source_code: true
  # Configuraciones que definen que se imprimen al terminar la ejecución de las pruebas
  print:
    table:
      # Configuración para imprimir un resumen del proceso realizado por los agentes
      summary: true
      # Configuración para imprimir un resumen detallado del proceso realizado por los agentes
      detailed: true
    column:
      failed_files: true
      files_load: true
      finish_in: true
      batch_run: true
      share_source_code: true
    failures:
      detailed: true
      summary: true
# Configuraciones compartidas entre Manager y Agent
general:
  # Configuración del nombre del archivo de código fuente comprimido enviado a los agentes
  # Obs.: Puede que NO sea útil para el usuario poder cambiar este nombre
  compressed_file_name: compressed_source_code
  # Configuraciones de logs
  log:
    # Configuración del log mostrado en la terminal
    stdout:
      # Define si se muestra el log de ejecución del programa en línea de comando. Puede ser true o false.
      # Por defecto siempre se imprimirá el log en un archivo dentro de la carpeta logs
      # Si se pone a true, interfiere con la barra de progreso del Manager, mejor tenerlo en false
      show: false
      # Define los colores del texto del log. Puede ser none (no muestra colores), severity (colorea código de error),
      # severity_date (colorea código de error y fecha), full (colorea el texto entero).
      colorize: full
    # Configuración del log guardado en los archivos .log
    file:
      # Puede ser none, severity o full
      colorize: full
  library:
    # Configuración de la librería de compresión a utilizar para comprimir el código fuente
    # Valores soportados: Sólo Zip hasta ahora
    compression: Zip
    # Configuración de la librería de pruebas unitarias a ejecutar
    # Valores soportados: Sólo Rspec hasta ahora
    unit_test: Rspec
  # Configuración de puertos
  ports:
    # Configuración del puerto a través del cual se realizará la primera comunicación entre Manager y Agent
    udp: 2000
    # Configuración del puerto a través del cual el Agent y el Manager intercambiarán las pruebas a ejecutar y los resultados de esa ejecución
    tcp: 2500
