# Este archivo .yml define ciertas configuraciones para la ejecución del sistema
# Configuración del Nombre del archivo de código fuente comprimido enviado a los agentes
# Obs.: Puede que no sea útil para el usuario poder cambiar este nombre
compressed_file_name: compressed_source_code
# Configuración de la cantidad de archivos de tests a ejecutar en cada tanda
test_files_by_runner: 30
# Configuración para especificar si se desea o no mostrar el progreso de envío de código fuente a los agentes
show_sharing_source_code_bar: true
# Configuración para imprimir la lista detallada de tests fallidos
print_failures_list: false
# Configuración para imprimir la lista resumida de tests fallidos
print_failed_examples: false
# Configuración para imprimir un resumen detallado del proceso realizado por los agentes
print_agents_detailed_summary: false
# Configuración para definir cada cuantos segundo el Manager enviará un broadcast UDP a la red para sondear agentes
udp_request_delay: 3
log:
  stdout:
    # Configuración que define si se muestra el log de ejecución del programa en línea de comando. Puede ser true o false.
    # Por defecto siempre se imprimirá el log en un archivo dentro de la carpeta logs
    # Si se pone a true, interfiere con la barra de progreso del Manager, mejor tenerlo en false
    show: false
    # Define los colores del texto del log. Puede ser none (no muestra colores), severity (colorea código de error),
    # severity_date (colorea código de error y fecha), full (colorea el texto entero).
    colorize: full
  file:
    colorize: full
library:
  # Configuración de la librería de compresión a utilizar para comprimir el código fuente
  # Valores soportados: Sólo Zip hasta ahora
  compression: Zip
  # Configuración de la librería de pruebas unitarias a ejecutar
  # Valores soportados: Sólo Rspec hasta ahora
  unit_test: Rspec
ports:
  # Configuración del puerto a través del cual se realizará la primera comunicación entre Manager y Agent
  udp: 2000
  # Configuración del puerto a través del cual el Agent y el Manager intercambiarán las pruebas a ejecutar y los resultados de esa ejecución
  tcp: 2500
