AllCops:
  Includes:
    - Gemfile
    - lib/**
    - spec/**
  Excludes:
    - bin/*
    - exe/*
Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Layout/LineLength:
  Max: 120
Style/StringLiterals:
  EnforcedStyle: double_quotes