require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

# Set default rake task, run 'rake install' command in CLI when run 'rake' command in CLI
# From:
# - https://medium.com/@stephenagrice/making-a-command-line-ruby-gem-write-build-and-push-aec24c6c49eb
task :default => :install

# build gem
# > rake build
task :build do
  system "gem build " + Liri::NAME + ".gemspec"
end

# install gem after build
# > rake install
task :install => :build do
  system "gem install " + Liri::NAME + "-" + Liri::VERSION + ".gem"
end

# publish gem after build
# > rake publish
task :publish => :build do
  system 'gem push ' + Liri::NAME + "-" + Liri::VERSION + ".gem"
end

# Clean compiled gem
# > rake clean
task :clean do
  system "rm *.gem"
end